version: "3.9"

services:
  app:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      DB_NAME: study_bot
      DB_USER: webshining
      DB_PASS: admin
      DB_HOST: postgres
      DB_PORT: 5432
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: webshining
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: study_bot