version: "3.9"

services:
  app:
    build: .
    restart: always
    entrypoint:
      - ./bin/entrypoint.sh
    depends_on:
      - db
      - rd
    environment:
      DB_NAME: study_bot
      DB_USER: webshining
      DB_PASS: admin
      DB_HOST: db
      DB_PORT: 5432
      RD_DB: 5
      RD_HOST: rd
      RD_PORT: 6379
  rd:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: webshining
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: study_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
volumes:
  postgres_data:
