version: "3.9"

services:
  app:
    build: .
    restart: always
    depends_on:
      - redis
    # environment:
    #   - RD_DB=5
    #   - RD_HOST=redis
    #   - RD_PORT=6379
  redis:
    image: redis
    volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"