[tool.poetry]
name = "study-bot"
version = "0.1.0"
description = ""
authors = ["Artem <artemilienkono@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.21"
peewee = "^3.15.1"
peewee-migrate = "^1.4.12"
environs = "^9.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
